// 1
function MultiplicatorUnitFailure() {
this.message = "Multiplication Error";
this.stack = (new Error()).stack;
}
MultiplicatorUnitFailure.prototype = Object.create(Error.prototype);

function primitiveMultiply(a, b) {
  if (Math.random() < 0.5)
    return a * b;
  else
    throw new MultiplicatorUnitFailure();
}

function reliableMultiply(a, b) {
try { console.log(primitiveMultiply(a,b)) } catch(e) {
  if(e) {
    console.log("OOps ! retrying !");
    reliableMultiply(a, b); }
  }
}


// 2
var box = {
  locked: true,
  unlock: function() { this.locked = false; },
  lock: function() { this.locked = true;  },
  _content: [],
  get content() {
    if (this.locked) throw new Error("Locked!");
    return this._content;
  }
};

function withBoxUnlocked(body) {
  // Your code here.
  try {
    box.unlock()
    body();
  }
  // catch(e){
  //   console.log("Error encountered!");
  // }
  finally {
    box.lock();
  }
}

withBoxUnlocked(function() {
  box.content.push("gold piece");
});

try {
  withBoxUnlocked(function() {
    throw new Error("Pirates on the horizon! Abort!");
  });
} catch (e) {
  console.log("Error raised:", e);
}
console.log(box.locked);
// â†’ true
